# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('account_holder', models.CharField(max_length=30)),
                ('account_type', models.CharField(max_length=20)),
                ('pancard_no', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('contact', models.BigIntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('branch_name', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('branch_address', models.CharField(max_length=150)),
                ('branch_contact', models.BigIntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField(default=None)),
                ('amount', models.IntegerField(default=None)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bankapp.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bankapp.Bank'),
        ),
    ]
